### ISSUE TITLE
Self-signup for the clojurians slack is broken

### ISSUE THREAD

**Issue by igufi** [clojurians/community-development#5]
Then slack invite @ clojurians.net is no longer active:

![image](https://user-images.githubusercontent.com/1605764/110205449-9d9a9780-7e80-11eb-9643-5136c423996f.png)

**Comment by seancorfield** [comment]
Yes, we know, but we don't have access to the clojurians.net web site to fix it right now.

For now, you can use this link (which will not expire but will only work for the first 2,000 signups):

👋  Let’s move this to Slack! We’ve got 20522 folks from the team there already. You can sign up here: https://join.slack.com/t/clojurians/shared_invite/zt-lsr4rn2f-jealnYXLHVZ61V2vdi15QQ

**Comment by igufi** [comment]
Thank you for the link. I'm all sorted now :)

**Comment by seancorfield** [comment]
I'd like to keep this open so others can find it more easily - and until we can solve the web site issue.

**Comment by seancorfield** [comment]
This has been fixed. The Admin team now have full control over the domain and we should be able to keep it working in the future!

**Comment by stefan-wullems** [comment]
Hey there. For me the http://clojurians.net/ does not work at the moment, nor does the invite above :).

**Comment by howonlee** [comment]
hey, the link isn't working anymore

**Comment by howonlee** [comment]
at this point you might consider having some sort of alert on it, looks like

**Comment by seancorfield** [comment]
The domain needed renewing. It's working now. The next renewal will be May 2026. We have a reminder in our calendar for that 🙂

**Comment by gaurav-arya** [comment]
Hey! I'm getting a "This link is no longer active" message using http://clojurians.net/.

**Comment by seancorfield** [comment]
I just tried that link and it works for me, redirecting me to Slack, but I can update the invite link behind it again -- it's about due for a refresh.

**Comment by seancorfield** [comment]
Updated with a new invite link so it should start working again, as soon as DNS propagates to your @gaurav-arya
