### ISSUE TITLE
Clojurians Slack - link no longer active from clojurians.net redirect

### ISSUE THREAD

**Issue by ThaisLasso** [clojurians/community-development#8]
I am trying to join the Clojurians Slack through http://clojurians.net and I get the following message: 
> This link is no longer active
> To join this workspace, you’ll need to ask the person who originally invited you for a new link.

I googled what I might be doing wrong and I found out that I could [open an issue here when that happens](https://www.reddit.com/r/Clojure/comments/lebevp/comment/gr310ca/?utm_source=share&utm_medium=web3x), and in hopes that this continues to be the appropriate mechanism, I am creating this issue.

**Comment by seancorfield** [comment]
We must have reached 400 new signups some time yesterday and Slack expired the previous link. Very frustrating that they limit the links so much these days.

The domain has been updated with a new invitation link but it may take an hour or so for DNS to propagate so if you try again later today, it should be working again.

In the meantime, you should be able to use this link directly https://join.slack.com/t/clojurians/shared_invite/zt-1sn68vi9d-qdfDzonsBuZpmbchBcfOBQ (it's what the domain will redirect to once DNS has propagated).

**Comment by ThaisLasso** [comment]
Frustrating indeed! I'm all set now, thank you :)
